/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Captures PNG-encoded screenshots of every connected monitor.
 *
 * ```ts
 * const screenshots: Screenshot[] = await captureAllMonitors()
 * ```
 */
export declare function captureAllMonitors(): Promise<Array<Screenshot>>

/**
 * Captures a PNG-encoded screenshot of the monitor with the given `id`.
 *
 * Returns a `Screenshot` containing monitor metadata and a `Buffer` with
 * the PNG data.
 *
 * ```ts
 * const screenshot: Screenshot = await captureMonitor(1)
 * // screenshot.data is a Buffer containing PNG bytes
 * ```
 */
export declare function captureMonitor(id: number): Promise<Screenshot>

/**
 * Returns metadata for the monitor with the given `id`.
 *
 * Throws a `MONITOR_NOT_FOUND` error if no monitor matches.
 *
 * ```ts
 * const monitor: Monitor = await getMonitorById(1)
 * ```
 */
export declare function getMonitorById(id: number): Promise<Monitor>

/**
 * Returns metadata for all connected monitors.
 *
 * ```ts
 * const monitors: Monitor[] = await getMonitors()
 * ```
 */
export declare function getMonitors(): Promise<Array<Monitor>>

/**
 * JavaScript-facing monitor metadata.
 *
 * A snapshot of monitor state at the time it was queried. This is a plain
 * data object — it does **not** hold a live reference to the OS resource.
 * Monitors can be disconnected or reconfigured at any time, so instances
 * may become stale. Use `captureMonitor(id)` or `getMonitorById(id)` to
 * re-query the OS for current state.
 *
 * ## Physical vs. logical coordinates
 *
 * The top-level geometry fields (`x`, `y`, `width`, `height`) are in
 * **physical pixels** — they always match the dimensions of a captured
 * screenshot buffer. This is the default because screenshot consumers
 * (image libraries, canvas drawing, file output) operate in physical pixels.
 *
 * The `logical*` fields (`logicalX`, `logicalY`, `logicalWidth`,
 * `logicalHeight`) represent the same geometry in **logical (DIP / CSS-point)
 * units** as the OS or window manager sees them. On a 2× Retina display a
 * 2560×1600 physical screen has 1280×800 logical dimensions.
 *
 * Both sets are always populated. You can convert between them with the
 * `scaleFactor`:
 *
 * ```ts
 * physical = logical * scaleFactor
 * logical  = physical / scaleFactor
 * ```
 *
 * ### Platform coordinate sources
 *
 * | Platform | Raw from OS | Physical | Logical |
 * |----------|-------------|----------|---------|
 * | macOS | `CGDisplayBounds` → logical pts | raw × scaleFactor | raw (passthrough) |
 * | Linux | XRandR raw ÷ scale → logical | raw × scaleFactor | raw (passthrough) |
 * | Windows | `DEVMODEW` → physical px | raw (passthrough) | raw ÷ scaleFactor |
 *
 * ### Platform name fields
 *
 * | Platform | `name` | `friendlyName` |
 * |----------|--------|----------------|
 * | macOS | `"Display #<model>"` (e.g. `"Display #16419"`) | `NSScreen.localizedName` (e.g. `"Built-in Retina Display"`) |
 * | Windows | Device path (e.g. `\\.\DISPLAY1`) | Monitor product name (e.g. `"LG UltraFine"`) |
 * | Linux | XRandR output (e.g. `"HDMI-1"`) | Same as `name` (X11 has no separate friendly name) |
 */
export interface Monitor {
  /**
   * OS-assigned monitor identifier. Stable within a single session but may
   * change across reboots or when monitors are reconnected.
   */
  id: number
  /**
   * System-level device or output name.
   *
   * - **macOS**: `"Display #<model_number>"` (e.g. `"Display #16419"`)
   * - **Windows**: device path (e.g. `\\.\DISPLAY1`)
   * - **Linux**: XRandR output name (e.g. `"HDMI-1"`, `"eDP-1"`)
   */
  name: string
  /**
   * Human-readable display name suitable for showing in a UI.
   *
   * - **macOS**: `NSScreen.localizedName` (e.g. `"Built-in Retina Display"`)
   * - **Windows**: monitor product name from EDID (e.g. `"LG UltraFine"`)
   * - **Linux**: same as `name` (X11 does not expose a separate friendly name)
   */
  friendlyName: string
  /**
   * Horizontal position of the monitor's top-left corner in **physical
   * pixels** within the virtual-screen coordinate space. This is the
   * default coordinate system — it matches captured screenshot dimensions.
   */
  x: number
  /**
   * Vertical position of the monitor's top-left corner in **physical
   * pixels** within the virtual-screen coordinate space.
   */
  y: number
  /**
   * Horizontal resolution in **physical pixels**. Matches the width of
   * a captured screenshot buffer for this monitor.
   */
  width: number
  /**
   * Vertical resolution in **physical pixels**. Matches the height of
   * a captured screenshot buffer for this monitor.
   */
  height: number
  /**
   * Horizontal position of the monitor's top-left corner in **logical
   * (DIP / CSS-point) units**. Equal to `x / scaleFactor`.
   */
  logicalX: number
  /**
   * Vertical position of the monitor's top-left corner in **logical
   * (DIP / CSS-point) units**. Equal to `y / scaleFactor`.
   */
  logicalY: number
  /**
   * Horizontal resolution in **logical (DIP / CSS-point) units**.
   * Equal to `width / scaleFactor`.
   */
  logicalWidth: number
  /**
   * Vertical resolution in **logical (DIP / CSS-point) units**.
   * Equal to `height / scaleFactor`.
   */
  logicalHeight: number
  /**
   * Display rotation in degrees. Common values: `0.0`, `90.0`, `180.0`,
   * `270.0`.
   */
  rotation: number
  /**
   * HiDPI / Retina scale factor. `1.0` for standard displays, `2.0` for
   * typical Retina or HiDPI configurations. Relates physical and logical
   * coordinates: `physical = logical × scaleFactor`.
   */
  scaleFactor: number
  /** Display refresh rate in Hz (e.g. `60.0`, `120.0`, `144.0`). */
  frequency: number
  /** Whether this is the primary (main) display as designated by the OS. */
  isPrimary: boolean
  /**
   * Whether this is a built-in display (e.g. a laptop panel). Falls back
   * to `false` on platforms that do not report this information.
   */
  isBuiltin: boolean
}

/**
 * JavaScript-facing screenshot result pairing monitor metadata with the
 * captured image data.
 *
 * The `data` buffer contains a **PNG-encoded** image by default. It can be
 * written to disk, served over HTTP, or passed directly to any image
 * library without additional processing.
 */
export interface Screenshot {
  /** Metadata of the monitor this screenshot was captured from. */
  monitor: Monitor
  /**
   * PNG-encoded image bytes. The buffer dimensions match the monitor's
   * physical `width` × `height`.
   */
  data: Buffer
}
