/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A rectangular region in a 2D coordinate space.
 *
 * Used to represent monitor geometry. The coordinate system (physical pixels
 * or logical DIP units) depends on context — see the `physical` and
 * `logical` fields on [`Monitor`].
 */
export interface Bounds {
  /** Horizontal position of the top-left corner. */
  x: number
  /** Vertical position of the top-left corner. */
  y: number
  /** Horizontal extent in the given coordinate system. */
  width: number
  /** Vertical extent in the given coordinate system. */
  height: number
}

/**
 * Captures PNG-encoded screenshots of every connected monitor.
 *
 * ```ts
 * const results: CaptureResult[] = await captureAllMonitors()
 * ```
 */
export declare function captureAllMonitors(): Promise<Array<CaptureResult>>

/**
 * Captures a PNG-encoded screenshot of the monitor with the given `id`.
 *
 * Returns a `CaptureResult` containing monitor metadata and a `Screenshot`
 * with the image dimensions and PNG-encoded `Buffer`.
 *
 * ```ts
 * const result: CaptureResult = await captureMonitor(1)
 * result.screenshot.size   // { width: 2560, height: 1600 }
 * result.screenshot.data   // <Buffer 89 50 4e 47 ...>
 * result.monitor.name      // "Built-in Retina Display"
 * ```
 */
export declare function captureMonitor(id: number): Promise<CaptureResult>

/**
 * The result of a capture operation — pairs monitor metadata with the
 * captured screenshot.
 *
 * Returned by `captureMonitor()` and `captureAllMonitors()`.
 *
 * ```ts
 * const result: CaptureResult = await captureMonitor(1)
 * result.monitor.name            // "Built-in Retina Display"
 * result.screenshot.size.width   // 2560
 * result.screenshot.data         // <Buffer 89 50 4e 47 ...>
 * ```
 */
export interface CaptureResult {
  /** Metadata of the monitor this screenshot was captured from. */
  monitor: Monitor
  /** The captured image with its dimensions and encoded bytes. */
  screenshot: Screenshot
}

/**
 * Returns metadata for the monitor with the given `id`.
 *
 * Throws a `MONITOR_NOT_FOUND` error if no monitor matches.
 *
 * ```ts
 * const monitor: Monitor = await getMonitorById(1)
 * ```
 */
export declare function getMonitorById(id: number): Promise<Monitor>

/**
 * Returns metadata for all connected monitors.
 *
 * ```ts
 * const monitors: Monitor[] = await getMonitors()
 * ```
 */
export declare function getMonitors(): Promise<Array<Monitor>>

/**
 * The encoding format of a captured screenshot.
 *
 * Indicates which image codec was used to encode `Screenshot.data`.
 *
 * | Value | MIME type | Notes |
 * |-------|-----------|-------|
 * | `"Png"` | `image/png` | Default. Lossless, pixel-perfect. |
 * | `"Jpeg"` | `image/jpeg` | Lossy. Smaller files. *(planned)* |
 * | `"WebP"` | `image/webp` | Lossy/lossless. Good compression. *(planned)* |
 * | `"Avif"` | `image/avif` | Best compression. *(planned)* |
 */
export declare const enum ImageFormat {
  /** PNG — lossless, pixel-perfect. Default format. */
  Png = 'Png',
  /** JPEG — lossy compression. */
  Jpeg = 'Jpeg',
  /** WebP — lossy or lossless. */
  WebP = 'WebP',
  /** AVIF — lossy or lossless, best compression. */
  Avif = 'Avif'
}

/**
 * JavaScript-facing monitor metadata.
 *
 * A snapshot of monitor state at the time it was queried. This is a plain
 * data object — it does **not** hold a live reference to the OS resource.
 * Monitors can be disconnected or reconfigured at any time, so instances
 * may become stale. Use `captureMonitor(id)` or `getMonitorById(id)` to
 * re-query the OS for current state.
 *
 * ## Physical vs. logical coordinates
 *
 * `physical` contains geometry in **physical pixels** — values that always
 * match the dimensions of a captured screenshot buffer. This is what you
 * want when working with image data (drawing, saving, pixel manipulation).
 *
 * `logical` contains the same geometry in **logical (DIP / CSS-point)
 * units** as the OS or window manager sees them. On a 2× Retina display a
 * 2560×1600 physical screen has 1280×800 logical dimensions. Physical and
 * logical values are identical on standard 1× displays.
 *
 * Both are always populated. Convert between them with `scaleFactor`:
 *
 * ```ts
 * physical = logical * scaleFactor
 * logical  = physical / scaleFactor
 * ```
 *
 * ### Platform name fields
 *
 * | Platform | `name` | `friendlyName` |
 * |----------|--------|----------------|
 * | macOS | `"Display #<model>"` (e.g. `"Display #16419"`) | `NSScreen.localizedName` (e.g. `"Built-in Retina Display"`) |
 * | Windows | Device path (e.g. `\\.\DISPLAY1`) | Monitor product name (e.g. `"LG UltraFine"`) |
 * | Linux | XRandR output (e.g. `"HDMI-1"`) | Same as `name` (X11 has no separate friendly name) |
 */
export interface Monitor {
  /**
   * OS-assigned monitor identifier. Stable within a single session but may
   * change across reboots or when monitors are reconnected.
   */
  id: number
  /**
   * System-level device or output name.
   *
   * - **macOS**: `"Display #<model_number>"` (e.g. `"Display #16419"`)
   * - **Windows**: device path (e.g. `\\.\DISPLAY1`)
   * - **Linux**: XRandR output name (e.g. `"HDMI-1"`, `"eDP-1"`)
   */
  name: string
  /**
   * Human-readable display name suitable for showing in a UI.
   *
   * - **macOS**: `NSScreen.localizedName` (e.g. `"Built-in Retina Display"`)
   * - **Windows**: monitor product name from EDID (e.g. `"LG UltraFine"`)
   * - **Linux**: same as `name` (X11 does not expose a separate friendly name)
   */
  friendlyName: string
  /**
   * Monitor geometry in **physical pixels**. Values match the dimensions
   * of captured screenshot buffers. Use this when working with image data.
   */
  physical: Bounds
  /**
   * Monitor geometry in **logical (DIP / CSS-point) units** as reported
   * by the OS window manager. Use this for UI layout and positioning.
   */
  logical: Bounds
  /**
   * Display rotation in degrees. Common values: `0.0`, `90.0`, `180.0`,
   * `270.0`.
   */
  rotation: number
  /**
   * HiDPI / Retina scale factor. `1.0` for standard displays, `2.0` for
   * typical Retina or HiDPI configurations. Relates physical and logical
   * coordinates: `physical = logical × scaleFactor`.
   */
  scaleFactor: number
  /** Display refresh rate in Hz (e.g. `60.0`, `120.0`, `144.0`). */
  frequency: number
  /** Whether this is the primary (main) display as designated by the OS. */
  isPrimary: boolean
  /**
   * Whether this is a built-in display (e.g. a laptop panel). Falls back
   * to `false` on platforms that do not report this information.
   */
  isBuiltin: boolean
}

/**
 * A captured screenshot — the image payload with its dimensions and format.
 *
 * `data` contains encoded image bytes in the format indicated by `format`
 * (PNG by default). It can be written to disk, served over HTTP, or passed
 * directly to any image library without additional processing.
 *
 * `size` reflects the **actual** pixel dimensions of the encoded image.
 * Use `size.width` and `size.height` to know the image dimensions without
 * inspecting the encoded bytes.
 *
 * `format` tells you which codec was used, so you can set the correct
 * `Content-Type` header or file extension without guessing.
 */
export interface Screenshot {
  /** Actual pixel dimensions of the encoded image. */
  size: Size
  /** The encoding format of `data` (e.g. `"Png"`). */
  format: ImageFormat
  /** Encoded image bytes in the format specified by `format`. */
  data: Buffer
}

/**
 * Image dimensions in pixels.
 *
 * Describes the extent of a captured image. For a full-monitor capture this
 * matches the monitor's `physical` bounds, but future region captures may
 * produce different dimensions.
 */
export interface Size {
  /** Image width in pixels. */
  width: number
  /** Image height in pixels. */
  height: number
}
